version: '3'

services:
  master:
    build: ./master
    command: python3 master.py
    volumes:
      - .:/master
    ports:
      - "3100:3100"
    depends_on:
      keeper:
        condition: service_healthy

  keeper:
    build: ./keeper
    command: python3 keeper.py
    volumes:
      - .:/keeper
    ports:
      - "3200:3200"
    depends_on:
      - reaper
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:3200" ]
      interval: 5s
      timeout: 10s
      start_period: 3s
      retries: 3

  reaper:
    build: ./reaper
    command: python3 reaper.py
    volumes:
      - .:/reaper
    ports:
      - "3300:3300"